name: ProjectsBase
version: '${project.version}'
main: com.zyneonstudios.nerotvlive.projectsbase.Main
api-version: 1.21
authors: [ nerotvlive ]
description: The base of Zyneon projects.

commands:
  author:
    aliases: [project,projects,projectsbase,zyneon,pb,pb26,projectsbase26]
  book:
    aliases: [buch,writable,feder,feather]
  broadcast:
    aliases: [bc,alert]
  character:
    aliases: [char,chareditor,charactereditor,editor,ceditor,name,job,rpname,rpjob,charakter]
  clearchat:
    aliases: [chatclear,cc,clearc,chatc]
  day:
  feed:
  fly:
  gamemode:
    aliases: [gm,spielmodus,sm]
  god:
  heal:
  invsee:
  maintenance:
  money:
  lock:
  lockmode:
  night:
  npc:
    aliases: [pnpc]
  ping:
  poweruser:
    aliases: [pu,mohistoperatorcommand,magmaoperatorcommand,moc,op,operator,superuser,su]
  rain:
  roleplay:
    aliases: [rp]
  say:
  shout:
    aliases: [s,schreien]
  speed:
  srl:
    aliases: [stop,srs,serverstop,serverrestart,serverreload,restart,rl,rs,reload,end]
  sun:
  team:
    aliases: [teammode]
  tell:
    aliases: [t,m,msg]
  thunder:
  trust:
  unlock:
  warp:
    aliases: [spawn]
  whisper:
    aliases: [w,f,flüstern]
  whitelist:
    aliases: [list,white-list]
  world:
    aliases: [welt,map,karte]